apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: logging
  name: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logging
    spec:
      containers:
      - image: busybox:latest
        name: logger
        resources: {}
status: {}
