namePrefix: uat-
resources:
  - ../../base

namespace: uat

commonLabels:
  feature: api

patches:
 - target:
    kind: Deployment
    name: my-app
   patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
