---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 4-demo-source
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: 4-demo
  url: https://github.com/ajayro45/bb-app-source/
