---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: 7-demo-source-oci
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 6.0.0-0bb2691
  secretRef:
    name: ghcr-auth
  url: oci://ghcr.io/ajayro45/bb-app
