---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: 8-demo-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ImageRepository/8-demo-image
  policy:
    semver:
      range: 7.0.x
