---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: demo-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-image
 policy:
  regex:
    pattern: '^.*$'  
