---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-infra-git
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./bitnami-sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-source-git
