namePrefix: dev-
resources:
  - ../../base

components:
  - ../../components  
namespace: dev

commonLabels:
  feature: api

patches: 
 - target:
    kind: Deployment
    name: my-app  
   patch: |-
      - op: replace
        path: /spec/replicas
        value: 1  
