apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app # <-- name of the Deployment in base (before patch)
# Rename the Deployment here
spec:
  replicas: 5
  template:
    spec:
      containers:
         - name: my-app
           image: haproxy
